name: aplikasi_kunci
description: Aplikasi kunci layar + lampu kedip
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flashlight: ^3.1.0 # ✅ Tambah paket lampu senter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true